### PR TITLE
Put comment hint on SQL columns for Enum type

### LINKED ISSUE #4: Generate diff migration always dump Enum columns
Example :

Creating the following initial table `third_party` : 

```
        'CREATE TABLE third_party (
              id SERIAL NOT NULL, 
              name VARCHAR(255) NOT NULL, 
              type VARCHAR(255) NOT NULL, 
              address VARCHAR(1024) DEFAULT NULL, 
              post_code VARCHAR(10) DEFAULT NULL, 
              city VARCHAR(128) DEFAULT NULL, 
              country VARCHAR(255) NOT NULL, 
              PRIMARY KEY(id))
          ');
```

Where `type` and `country` are both of them BackedEnum. If I execute this migration, and regenarate a diff migration, it will always reconfigure this 2 columns definition : 

```
     ALTER TABLE third_party ALTER type TYPE VARCHAR(255);
     ALTER TABLE third_party ALTER type DROP DEFAULT;
     ALTER TABLE third_party ALTER country TYPE VARCHAR(255);
     ALTER TABLE third_party ALTER country DROP DEFAULT;
```

By searching on the migrations packages, the changes seems to be detected like this (for `country`) : 

Before change : 
```
^ Doctrine\DBAL\Schema\Column^ {#347
  #_name: "country"
  #_namespace: null
  #_quoted: false
  #_type: Doctrine\DBAL\Types\StringType^ {#123}
  #_length: 255
  #_precision: 10
  #_scale: 0
  #_unsigned: false
  #_fixed: false
  #_notnull: true
  #_default: null
  #_autoincrement: false
  #_platformOptions: []
  #_columnDefinition: null
  #_comment: null
  #_customSchemaOptions: []
}
```

After change : 
```
Doctrine\DBAL\Schema\Column^ {#302
  #_name: "country"
  #_namespace: null
  #_quoted: false
  #_type: BenTools\Doctrine\NativeEnums\Type\NativeEnum^ {#115
    -name: "App\Enum\CountryEnum"
    -class: "App\Enum\CountryEnum"
    -type: BenTools\Doctrine\NativeEnums\Type\BackedEnumType^ {#116
      +name: "STRING"
    }
  }
  #_length: null
  #_precision: 10
  #_scale: 0
  #_unsigned: false
  #_fixed: false
  #_notnull: true
  #_default: null
  #_autoincrement: false
  #_platformOptions: array:1 [
    "version" => false
  ]
  #_columnDefinition: null
  #_comment: null
  #_customSchemaOptions: []
}
```

I'm trying to find a solution right now.

### PR DESCRIPTION
**Pull request by jonbk**
#4

### CODE REVIEW

**Comment by jonbk** [comment]
It will be great if the code would be released if the PR is approved :) 

Thanks ;)

**Comment by bpolaszek** [comment]
Hi @jonbk - thank you for spotting & fixing this!
CI yells about coverage - you can safely add a `@codeCoverageIgnore` PHPDoc block on top of the `requiresSQLCommentHint()` method.

FYI the Doctrine Team is currently working on an out-of-the-box [support for Backed Enums](https://github.com/doctrine/orm/pull/9304), which may deprecate this package in a near future. Stay tuned!

**Comment by ghost** [comment]
> FYI the Doctrine Team is currently working on an out-of-the-box [support for Backed Enums](https://github.com/doctrine/orm/pull/9304), which may deprecate this package in a near future. Stay tuned!

Yes I do know this is in progress in Doctrine Team, but there is no visibility in when it will be released, so I discovered your package working perfectly and allow me using native Enum right now :) 

Many thanks.

**Review by bpolaszek — APPROVED** [review]
Thank you @jonbk.

**Pull request merged**
